apiVersion: v1
kind: Namespace
metadata:
  name: frontend-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: frontend-ns

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: frontend-envoy-config
  namespace: frontend-ns
data:
  envoy.json: |-
    {
      "listeners": [
        {
          "address": "tcp://0.0.0.0:80",
          "filters": [
            {
              "type": "read",
              "name": "http_connection_manager",
              "config": {
                "codec_type": "auto",
                "stat_prefix": "ingress_http",
                "route_config": {
                  "virtual_hosts": [
                    {
                      "name": "backend",
                      "domains": ["*"],
                      "routes": [
                        {
                          "timeout_ms": 0,
                          "prefix": "/service/1",
                          "cluster": "service1"
                        },
                        {
                          "timeout_ms": 0,
                          "prefix": "/service/2",
                          "cluster": "service2"
                        }
                      ]
                    }
                  ]
                },
                "filters": [
                  {
                    "type": "decoder",
                    "name": "router",
                    "config": {}
                  }
                ]
              }
            }
          ]
        }
      ],
      "admin": {
        "access_log_path": "/dev/null",
        "address": "tcp://0.0.0.0:8001"
      },
      "cluster_manager": {
        "clusters": [
          {
            "name": "service1",
            "connect_timeout_ms": 250,
            "type": "strict_dns",
            "lb_type": "round_robin",
            "features": "http2",
            "hosts": [
              {
                "url": "tcp://service1.backend-ns:80"
              }
            ]
          },
          {
            "name": "service2",
            "connect_timeout_ms": 250,
            "type": "strict_dns",
            "lb_type": "round_robin",
            "features": "http2",
            "hosts": [
              {
                "url": "tcp://service2.backend-ns:80"
              }
            ]
          }
        ]
      }
    }


---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: envoy-frontend
  namespace: frontend-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: envoy-frontend
    spec:
      containers:
      - name: envoy-frontend
        image: lyft/envoy:latest
        command:
        - "envoy"
        - "-c"
        - "/etc/envoy/envoy.json"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-envoy-config
          mountPath: /etc/envoy/
      serviceAccount: frontend-sa
      volumes:
      - name: frontend-envoy-config
        configMap:
          name: frontend-envoy-config

---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: frontend-ns
spec:
  selector:
    app: envoy-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
